/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.baskel.utils;

/**
 *
 * @author dell
 */
public class AutoCompleteAdresse {

    public static String[] adrGov = {
        "Ariana La Soukra",
        "Ariana Ariana",
        "Ariana Raoued",
        "Ariana Kalâat el-Andalous",
        "Ariana Sidi Thabet",
        "Ariana Ettadhamen-Mnihla",
        "Béja El Maâgoula",
        "Béja Beja",
        "Béja Zahret Medien",
        "Béja Nefza",
        "Béja Téboursouk",
        "Béja Testour",
        "Béja Goubellat",
        "Béja Majaz al Bab",
        "Ben Arous El Mourouj ",
        "Ben Arous Ben arous ",
        "Ben Arous Hammam Lif ",
        "Ben Arous Ezzahra ",
        "Ben Arous Hammam Chott",
        "Ben Arous Bou Mhel el-Bassatine",
        "Ben Arous Radès",
        "Ben Arous Mégrine",
        "Ben Arous Mohamedia-Fouchana",
        "Ben Arous Mornag",
        "Ben Arous Khalidia",
        "Bizerte Bizerte",
        "Bizerte sejnane",
        "Bizerte Mateur",
        "Bizerte Menzel Bourguiba",
        "Bizerte Tinja",
        "Bizerte Ghar el Melah",
        "Bizerte Aousja",
        "Bizerte Menzel jemil",
        "Bizerte Menzel Abderhmane",
        "Bizerte El Alia",
        "Bizerte Ras Jebal",
        "Bizerte Metline",
        "Bizerte Raf Raf",
        "Gafsa Gafsa",
        "Gafsa El Ksar",
        "Gafsa Moulares",
        "Gafsa Redeyef",
        "Gafsa Metlaoui",
        "Gafsa Mdhila",
        "Gafsa El guettar",
        "Gafsa Sened",
        "Gabes Gabes",
        "Gabes Ghenini nahal",
        "Gabes Ghannouch",
        "Gabes Metouia",
        "Gabes Oudhref",
        "Gabes El Hamma",
        "Gabes Matmata",
        "Gabes Nouvelle Matmata",
        "Gabes Mareth",
        "Gabes Zarat",
        "Jendouba Jendouba",
        "Jendouba Bou Salem",
        "Jendouba Tabarka",
        "Jendouba Ain Drahem",
        "Jendouba Fernana",
        "Jendouba Beni Mtir",
        "Jendouba Ghardimao",
        "Jendouba Oued Mliz",
        "Kairouan Kairouan",
        "Kairouan Chebika",
        "Kairouan Sbikha",
        "Kairouan Oueslatia",
        "Kairouan Ain Djeloula",
        "Kairouan Haffouz",
        "Kairouan Alaa",
        "Kairouan Hajeb El Ayoun",
        "Kairouan NAsrallah",
        "Kairouan Menzel Mehiri",
        "Kairouan Echrarda",
        "Kairouan Bou Hajla",
        "Kasserine Kassrine",
        "Kasserine Sbeitla",
        "Kasserine Sbiba",
        "Kasserine Jedelienne",
        "Kasserine Thala",
        "Kasserine Haidra",
        "Kasserine Foussana",
        "Kasserine Feriana",
        "Kasserine Thelepte",
        "Kasserine Magel Bel Abbes",
        "Sidi Bouzid Sidi Bouzid",
        "Sidi Bouzid Jilma",
        "Sidi Bouzid Cebalet",
        "Sidi Bouzid Bir el hafey",
        "Sidi Bouzid Sidi ali ben aoun",
        "Sidi Bouzid Menzel bouzaine",
        "Sidi Bouzid Meknassey",
        "Sidi Bouzid Mezzouna",
        "Sidi Bouzid Regueb",
        "Sidi Bouzid Oueld haffouz",
        "Kebili Kebili",
        "Kebili Djemma",
        "Kebili Douz",
        "Kebili El golaa",
        "Kebili Souk lahad",
        "Kef El kef",
        "Kef Nebeur",
        "Kef Touiref",
        "Kef Sakiet sidi youssef",
        "Kef Tajerouine",
        "Kef Menzel salem",
        "Kef Kalaat es senam",
        "Kef Kalaat khasba",
        "Kef Jerissa",
        "Kef El ksour",
        "Kef Dahmani",
        "Kef Sers",
        "Mahdia Mahdia",
        "Mahdia Rejiche",
        "Mahdia bou merdes",
        "Mahdia ouled chamedk",
        "Mahdia ghorbane",
        "Mahdia hebira",
        "Mahdia esouassia",
        "Mahdia el djem",
        "Mahdia kerker",
        "Mahdia chebba",
        "Mahdia mellouleche",
        "Mahdia sidi alouana",
        "Mahdia ksour essef",
        "Mahdia el bradaa",
        "Manouba Manouba",
        "Manouba Den Den",
        "Manouba Douar hicher",
        "Manouba Oued elil",
        "Manouba Mornaguia",
        "Manouba Borj el amri",
        "Manouba Djedeida",
        "Manouba Tebourba",
        "Manouba El battan",
        "Medenine Medenine",
        "Medenine Beni khedache",
        "Medenine Ben guerdane",
        "Medenine Zarzis",
        "Medenine Houmt el souk",
        "Medenine Midoun",
        "Medenine Ajim",
        "Monastir Monastir",
        "Monastir khniss",
        "Monastir ouerdanine",
        "Monastir sahline mootmar",
        "Monastir sidi ameur",
        "Monastir zeramdine",
        "Monastir beni hassen",
        "Monastir ghenada",
        "Monastir jemmal",
        "Monastir menzel kamel",
        "Monastir zaouiet kontoch",
        "Monastir bembla mnara",
        "Monastir menzel ennour",
        "Monastir el masdour",
        "Monastir moknine",
        "Monastir sedi bennour",
        "Monastir menzel farsi",
        "Monastir amiret el fhoul",
        "Monastir amiret touazra",
        "Monastir emiret el hojjaj",
        "Monastir cherahil",
        "Monastir bekalta",
        "Monastir teboulba",
        "Monastir ksar hellal",
        "Monastir ksibet el mediouni",
        "Monastir benen bodher",
        "Monastir touza",
        "Monastir sayada",
        "Monastir lemta",
        "Monastir bouhjar",
        "Monastir menzel hayet",
        "Nabeul Nabeul",
        "Nabeul Dar chaabane",
        "Nabeul beni khiar",
        "Nabeul el maamoura",
        "Nabeul somaa",
        "Nabeul korba",
        "Nabeul tazerka",
        "Nabeul menzel temime",
        "Nabeul menzel horr",
        "Nabeul el mida",
        "Nabeul kelibia",
        "Nabeul azmour",
        "Nabeul hammam ghezeze",
        "Nabeul dar allouch",
        "Nabeul el haouria",
        "Nabeul takelsa",
        "Nabeul soliman",
        "Nabeul korbous ",
        "Nabeul menzel bouzelfa",
        "Nabeul hammamet",
        "Sfax sfax",
        "Sfax sakiet ezzit",
        "Sfax chihia",
        "Sfax sakiet eddair",
        "Sfax gremda",
        "Sfax el ain",
        "Sfax thyna",
        "Sfax agareb",
        "Sfax jebiniana",
        "Sfax el hencha",
        "Sfax menzel chaker",
        "Sfax chraiba",
        "Sfax skhira",
        "Sfax mahares",
        "Sfax kerkenaah",
        "Siliana silianaa",
        "Siliana bou arada",
        "Siliana gaafour",
        "Siliana el krib",
        "Siliana sidi bou rouis",
        "Siliana maktar",
        "Siliana kesra",
        "Siliana bargou",
        "Siliana el aroussa",
        "Sousse sousse",
        "Sousse ksibet thrayet",
        "Sousse ezzouhour",
        "Sousse hammam sousse",
        "Sousse akouda",
        "Sousse kalaa l kbira",
        "Sousse sidi bou ali",
        "Sousse hergla",
        "Sousse enfidha",
        "Sousse bouficha",
        "Sousse sidi el hani",
        "Sousse msaken",
        "Sousse kalaa seghira",
        "Sousse messadine",
        "Sousse kondar",
        "Tataouine tataouine",
        "Tataouine bir lahmar",
        "Tataouine ghomrassen",
        "Tataouine dehiba",
        "Tataouine remada",
        "Tozeur Tozeur",
        "Tozeur degache",
        "Tozeur hamet jerid",
        "Tozeur nafta",
        "Tozeur tamerza",
        "Tunis Tunis",
        "Tunis le Bardo",
        "Tunis Le kram",
        "Tunis La goulette",
        "Tunis Carthage",
        "Tunis Sidi bou said",
        "Tunis La marsa",
        "Tunis Sidi hassine",
        "Zaghouan Zaghouan",
        "Zaghouan Zriba",
        "Zaghouan Bir Mcherga",
        "Zaghouan Djebel oust",
        "Zaghouan El fahs",
        "Zaghouan Nadhour",};
    public static String[] grosMots = {
        "bite", "baisable", "baise", "baiser", "bander", "branler", "branlette", "bordel", "burnes", "chatte", "chiant", "Chiante", "chiasse",
        "chier", "chiottes", "con", "conne", "connerie", "coucougnettes", "couille", "couillu", "cul", "déconner", "déconneur",
         "emmerder", "emmerdant", "emmerdante", "emmerdeur", "emmerdeuse", "empapaouter", "enculer", "entuber", "faire chier",
        "faire une pipe", "foutoir", "foutre", "foutre le camp", "foutu", "foutue", "gueule", "gueuler", "merde", "merder", "merdier", "merdique",
         "niquer", "nique ta mère", "pisser", "putain", "pute", "roubignoles", "roupettes", "roustons", "se démerder",
        "s’emmerder", "se faire chier", "se faire sauter", "sucer", "ta gueule", "tirer un coup", "turlutte", "zigounette", "fais chier", "je te saute",
        "zob","fuck","fuck you","slut","homosexuel","bicth"};

    public static String[] getAdrGov() {
        return adrGov;
    }

    public static void setAdrGov(String[] adrGov) {
        AutoCompleteAdresse.adrGov = adrGov;
    }

    public static String[] getGrosMots() {
        return grosMots;
    }

    public static void setGrosMots(String[] grosMots) {
        AutoCompleteAdresse.grosMots = grosMots;
    }
     public static boolean nb( String com){
        String[] splitString = com.split(" ");
        for (String wordString : splitString) {
            for (String wordArray : grosMots) {
                if (wordString.equalsIgnoreCase(wordArray)) {                    
                    return false;
                }
            }
        }
        return true;
        
    }

}
